### ISSUE TITLE
Bootstrapify current metacello

### ISSUE THREAD

**Issue by krono** [dalehenrich/metacello-work#322]
#316 fixed a crucial dependency for Squeak, but it is necessary that the current state is incorporated into the mcz-based bootstrap (There is no trace of metacello in Squeak, yet)

**Comment by dalehenrich** [comment]
Hmmm, I guess I didn't look to closely at the work done for #316:) If this stuff is needed for bootstrapping then I do not want to create a new version of Metacello (1.0-beta.32.2). Instead I would want to slip stream the change into the 1.0-beta32.1 and then after all of the tests are green on the configuration branch I would copy the ConfigurationOfMetacello package to the three standard configuration locations, GemSource, SmalltalkHub and SqueakSource (I think) ... I should probably give you permissions to those repositories so that I am not a single point of failure.

**Comment by krono** [comment]
Good you pushed me to write this :)
Can you give me a glimpse of what the slip-streaming involves?

**Comment by dalehenrich** [comment]
Haha, yep!

just do the necessary configuration changes directly in the baseline and/or version for 1.0-beta32.1 ... I've left 1.0-beta32.1 in development, because the requirements for loading from github do change over time and I want to avoid getting into a version number race where the previewBootstrap version approaches the github versions in ConfigurationOfMetacelloPreview (there is already a bit of overlap there:)

**Comment by krono** [comment]
I _just_ understood what to do.

**Comment by dalehenrich** [comment]
Need to deploy/publish the configurations ... @krono, could you give me your username for GemSource, SqueakSource, SS3 and SmalltalkHub ... when I do deploy these puppies I'll add you to the various Metacello repos...

**Comment by krono** [comment]
topa everywehre :)

**Comment by dalehenrich** [comment]
@krono, @fniephaus, I've pushed ConfigurationOfMetacello-topa.802 to the 4 standard deployment repositories. So the ssh errors should go away ...

@krono, I've added you as an admin/contributer/dev for all of the repos, so now you can deploy the configuration next time and not have to wait 4 months:)

Below is the tODE expression for doing the deploy:

```
mc copy ConfigurationOfMetacello-topa.802 github://dalehenrich/metacello-work:configuration http://www.squeaksource.com/MetacelloRepository http://smalltalkhub.com/mc/dkh/metacello/main http://seaside.gemtalksystems.com/ss/metacello http://seaside.gemtalksystems.com/ss/MetacelloRepository
```

**Comment by dalehenrich** [comment]
:)
