### ISSUE TITLE
Loading a PetitJava into the Pharo 4 depends on the version of a baseline.

### ISSUE THREAD

**Issue by kursjan** [dalehenrich/metacello-work#342]
I think there is a bug in the Monticello used in Pharo 4, please inspect:

    Gofer new smalltalkhubUser: 'Moose' project: 'PetitJava';
        configurationOf: #PetitJava; load.
   
    (ConfigurationOfPetitJava project version: #development) record  load asString.

Result will look like this:
```
a MetacelloNullRecordingMCSpecLoader(linear load : 
	linear load : 0.1-baseline [ConfigurationOfPetitJava]
		load : ConfigurationOfPetitParser
	atomic load : 0.1-baseline [ConfigurationOfPetitJava]
		load : PetitJava
		atomic load : 1.12-baseline [ConfigurationOfPetitParser]
			load : PetitParser
			load : PetitTests
	atomic load : 0.1-baseline [ConfigurationOfPetitJava]
		load : PetitJava
		atomic load : 1.12-baseline [ConfigurationOfPetitParser]
			load : PetitParser
			load : PetitTests)
```

Yet, if you change a baseline to 1.7 (just a copy-paste of 1.12) in the ConfigurationOfPetitParser>>development: from:

    spec for: #'pharo4.x' version: '1.12-baseline'.

to: 
    
    spec for: #'pharo4.x' version: '1.7-baseline'.

The result looks like this:
```
a MetacelloNullRecordingMCSpecLoader(linear load : 
	linear load : 0.1-baseline [ConfigurationOfPetitJava]
		load : ConfigurationOfPetitParser
	atomic load : 0.1-baseline [ConfigurationOfPetitJava]
		load : PetitJava
		atomic load : 1.8-snapshot [ConfigurationOfPetitParser]
			load : PetitParser-YuriyTymchuk.232
			load : PetitTests-AndreHora.47
			load : PetitAnalyzer-DiegoLont.46
	atomic load : 0.1-baseline [ConfigurationOfPetitJava]
		load : PetitJava)
```

The versions from the 1.8-snapshot are rather old and do not work with in Pharo 4. We had to create a mythical 1.12-baseline to get proper packages loaded.

**Comment by kursjan** [comment]
I checked with the fix for https://github.com/dalehenrich/metacello-work/issues/339, it does not work as well.

**Comment by dalehenrich** [comment]
@kursjan, thanks for the bug report ... I'm not quite sure what the issue is ... what is the expected result?

Also, I see that there is 1.8-snapshot showing up ... I think that snapshots are things that have been cooked with the express purpose of "forcing" Metacello to load certain versions and I assume that that might be what's going on here .... 

But again, I'm not sure which result is "incorrect"

**Comment by kursjan** [comment]
My point is that it is strange that the load differs depending solely on the version of a baseline. I expect two identical baselines with different number to load the same set of packages, perhaps I am missing some point somewhere?

Furthermore, I do not understand, how does it happen, that 1.8-snapshot (of PetitParser) is loaded, when, ConfigurationOfPetitJava requires development version of PetitParser, and the development is specified as:

    spec for: #'pharo4.x' version: '1.7-baseline'.

**Comment by dalehenrich** [comment]
@kursjan For the answer to that question you'll have to ask the maintainers of the ConfigurationOfPetitParser ... the line in baseline17::

```Smalltalk
		self populateSpec: spec with: self snapshot1.
```

is not really supposed to be used in a Metacello spec ... I don't prevent tricks like this, but I think that in general it is just a bad idea, because it can catch folks like you by surprise when a specification executes arbitrary smalltalk ...

baseline112: has no "arbitrary smalltalk" and thus behaves as expected ... because of that method, the two baselines are anything but `identical` ...

**Comment by kursjan** [comment]
@dalehenrich Thanks for the tip, you were right. After removing the snapshots, everything works like a charm.
