### ISSUE TITLE
Provide better way to customise error msgs so that colour coding can be added to things like Travis

### ISSUE THREAD

**Issue by macta** [dalehenrich/metacello-work#442]
I opened an enhancement on SmalltalkCI as I noticed that its not easy to spot some of the error messages in the Travis logs. and was told that Metacello produces the error I felt should be coloured. Is it possible to provide an easy hook for consuming tools to better do this.

e.g. For me It's confusing that a possible error like an undeclared class (due to a bad package prereq baseline of) isn't very visible in the Travis logs.

Fetched -> Lambda-cypress.1 --- filetree:///home/travis/build/macta/PharoLambda [:] --- filetree:///home/travis/build/macta/PharoLambda
Lambda class>>processJSON: (NeoJSONReader is Undeclared)

Loaded -> Lambda-cypress.1 --- filetree:///home/travis/build/macta/PharoLambda [:] --- cache
...finished baseline

The third line (NeoJSONReader is Undeclared) should be red.

SmalltalkCI should be able to somehow specify that important errors generate an Ansi color code prefix so that error msgs stand out in the  logs (see: https://blog.travis-ci.com/2014-04-11-fun-with-logs/  - "Add a dash of colour")

**Comment by dalehenrich** [comment]
I would think that SmalltalkCI should be able to add it's own coloring for Warnings with code that is similar to [this](https://github.com/hpi-swa/smalltalkCI/blob/e109441b1871c4cef7842cebfbef083344325619/repository/SmalltalkCI-Core.package/SCIMetacelloLoadSpec.class/instance/basicLoadProjectOn..st#L13-L22), i.e., handle the Warning and write a customized error message instead of letting the default Warning handler write the message ...
